name: better_commit
description: Let's AI write a Better Commit. Better Commit is a Dart package that uses AI to generate meaningful commit messages based on your code changes.
version: 1.3.0
repository: https://github.com/hosseinshaya/better_commit

environment:
  sdk: ^3.5.0

dependencies:
  dcli: ^6.0.5
  google_generative_ai: ^0.4.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0

executables:
  better_commit:
  better-commit: better_commit
