name: better_commit
description: Let's AI write a Better Commit.
version: 1.1.0
repository: https://github.com/hosseinshaya/better_commit

environment:
  sdk: ^3.5.0

dependencies:
  dcli: ^6.0.5
  google_generative_ai: ^0.4.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0

executables:
  better-commit: bin/better_commit.dart